# Generated by Django 4.0.3 on 2022-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPI', '0002_alter_task_taskowner_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_info',
            field=models.TextField(max_length=80),
        ),
    ]
