# Generated by Django 4.0.3 on 2022-08-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPI', '0003_alter_task_task_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_info',
            field=models.TextField(max_length=100),
        ),
    ]
